#pragma once

#include <cstdio>

enum Token {
	TOKEN_TYPE_SPEC,
	TOKEN_BASIC_TYPE,
	TOKEN_BOOLEAN_OP,
	TOKEN_BASIC_OP,
	TOKEN_IDENT_DECL,
	TOKEN_EXPR_CLOSE,
	TOKEN_ARG_DELIM,
	TOKEN_CONST,
	TOKEN_SCOPE_BEGIN,
	TOKEN_SCOPE_END,
	TOKEN_FUNC_BRACE_BEGIN,
	TOKEN_FUNC_BRACE_END,
	TOKEN_ASSIGN,
	TOKEN_FUNC,
	TOKEN_FLOW,
	TOKEN_PRINT,
	TOKEN_GEN,
	TOKEN_ARG_SECTION_DECL,
	TOKEN_BODY_SECTION_DECL,
	TOKEN_RET,
	TOKEN_MUTATION,
	TOKEN_EVAL_DATASET,
	TOKEN_EVAL_RES,
	TOKEN_IDENT,
	TOKEN_EXIT,
	TOKEN_ERROR,
};
